# Generated by Django 3.1.7 on 2021-03-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_connect_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='username',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='connect',
            old_name='content',
            new_name='insta_content',
        ),
        migrations.RenameField(
            model_name='connect',
            old_name='link',
            new_name='insta_link',
        ),
        migrations.RenameField(
            model_name='connect',
            old_name='icon_code',
            new_name='linkedin_content',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='social',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='connect',
            name='insta_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='linkedin_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='linkedin_link',
            field=models.URLField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='twitter_content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='twitter_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='twitter_link',
            field=models.URLField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
