# Generated by Django 3.1.7 on 2021-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210305_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='email_content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
