# Generated by Django 3.1.7 on 2021-03-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_connect_email_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='email_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='email_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
