# Generated by Django 3.1.7 on 2021-03-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
